{{- $namespace := .Release.Namespace -}}
{{- $fullName := include "fortio.fullname" . -}}
{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.genSecret }}
{{- with .Values.ingress.tls.genSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-tls
  namespace: {{ $namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .cert }}
  tls.key: {{ .key }}
{{- end }}
{{- end }}

{{- if and .Values.ingress.iap.enabled .Values.ingress.iap.genSecret }}
{{- with .Values.ingress.iap.genSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-iap
  namespace: {{ $namespace }}
type: Opaque
data:
  client_id: {{ .clientId }}
  client_secret: {{ .clientSecret }}
{{- end }}
{{- end }}
