{{- if .Values.service.enabled -}}
{{- $type := .Values.service.type | default "ClusterIP" }}
{{- $fullName := include "fortio.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  annotations:
    {{- if and .Values.service.ilb.enabled (contains "LoadBalancer" $type) }}
    cloud.google.com/load-balancer-type: internal
    {{- end }}
    {{- if .Values.service.http2.enabled }}
    cloud.google.com/app-protocols: '{"grpc":"HTTP2","http":"HTTP","https":"HTTP2"}'
    {{- end }}
    {{- if .Values.ingress.neg.enabled }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
    {{- if .Values.ingress.iap.enabled }}
    beta.cloud.google.com/backend-config: '{"ports": {"default":"{{ $fullName }}"}}'
    {{- end }}
  labels:
    app: {{ template "fortio.name" . }}
    chart: {{ template "fortio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- with .Values.service }}
  {{- if .headless.enabled }}
  type: ClusterIP
  clusterIP: None
  {{- else }}
  type: {{ $type }}
  sessionAffinity: {{ .sessionAffinity | default "None" }}
    {{- if or (contains "LoadBalancer" $type) (contains "NodePort" $type ) }}
  externalTrafficPolicy: {{ .externalTrafficPolicy | default "Cluster" }}
    {{- end }}
  {{- end }}
  ports:
    {{- if .externalPort.grpc }}
    - port: {{ .externalPort.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
    {{- if .externalPort.http }}
    - port: {{ .externalPort.http }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
    {{- if .externalPort.https }}
    - port: {{ .externalPort.https }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  {{- end }}
  selector:
    app: {{ template "fortio.name" . }}
    release: {{ .Release.Name }}
{{- end }}
