apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fortio.fullname" . }}
  labels:
    app: {{ template "fortio.name" . }}
    chart: {{ template "fortio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/service.yaml") . | sha256sum }}
spec:
  minReadySeconds: 30
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fortio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fortio.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - server
            - -logtostderr
            - -v=2
            - -redirect-port=disabled
            - -cert=/tls/tls.crt
            - -key=/tls/tls.key
            - -data-dir=/data
          ports:
            - name: grpc
              containerPort: 8079
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8082
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
# [START resources]
          resources:
{{ toYaml .Values.resources | indent 12 }}
# [END resources]
          volumeMounts:
# [START customTLS mount]
          {{- if .Values.customTLS.enabled }}
            - name: tls
              mountPath: /tls
          {{- end }}
# [END customTLS mount]
# [START dataVolumes mount]
          {{- with .Values.dataVolumes }}
            {{- if .enabled }}
              {{- range .volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- end }}
            {{- end }}
          {{- end }}
# [END dataVolumes mount]
      volumes:
# [START customTLS vol]
      {{- with .Values.customTLS }}
        {{- if .enabled }}
        - name: tls
          secret:
            secretName: {{ .secret }}
        {{- end }}
      {{- end }}
# [END customTLS vol]
# [START dataVolumes ]
      {{- with .Values.dataVolumes }}
        {{- if .enabled }}
          {{- range .volumes }}
        - name: {{ .name }}
{{ toYaml .disk | indent 10 }}          
          {{- end }}
        {{- end }}
      {{- end }}
# [END dataVolumes ]
# [START nodeSelector]
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
# [END nodeSelector]
# [START affinity]
      affinity:
      {{- with .Values.nodeAffinity }}
        nodeAffinity:
        {{- if .soft }}
{{ toYaml .soft | indent 10 }}
        {{- end }}
        {{- if .hard }}
{{ toYaml .hard | indent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.podAffinity }}
        podAffinity:
        {{- if .soft }}
{{ toYaml .soft | indent 10 }}
        {{- end }}
        {{- if .hard }}
{{ toYaml .hard | indent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.podAntiAffinity }}
        {{- if .soft }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "fortio.name" $ }}
                - key: release
                  operator: In
                  values:
                  - {{ $.Release.Name }}
              topologyKey: "kubernetes.io/hostname"
        {{- end }}
        {{- if .hard }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ template "fortio.name" $ }}
              - key: release
                operator: In
                values:
                - {{ $.Release.Name }}
            topologyKey: "kubernetes.io/hostname"
        {{- end }}
      {{- end }}
# [END affinity]
# [START tolerations]
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
# [END tolerations]