apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fortio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fortio.name" . }}
    chart: {{ template "fortio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/service.yaml") . | sha256sum }}
spec:
  minReadySeconds: 30
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fortio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fortio.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
# [START app container]
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - server
            - -logtostderr
            - -v=2
            - -redirect-port=disabled
            - -cert=/tls/tls.crt
            - -key=/tls/tls.key
            - -data-dir=/data
          ports:
            - name: grpc
              containerPort: 8079
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8082
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          # [START resources]
          resources:
{{ toYaml .Values.resources | indent 12 }}
          # [END resources]
          volumeMounts:
            # [START tls mount]
            {{- if .Values.tls.enabled }}
            - name: tls
              mountPath: /tls
            {{- end }}
            # [END tls mount]
            # [START data mount]
            {{- if .Values.data.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
            # [END data mount]
      volumes:
        # [START tls secret]
        {{- if .Values.tls.enabled }}
        - name: tls
          secret:
            secretName: {{ .Values.tls.secretName }}
        {{- end }}
        # [END tls secret]
        # [START data volume]
        {{- if .Values.data.enabled }}
        - name: data
{{ toYaml .Values.data.volume | indent 10 }}
        {{- end }}
        # [END data volume ]
      # [START nodeSelector]
        {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
        {{- end }}
      # [END nodeSelector]
      # [START affinity]
      affinity:
      {{- with .Values.nodeAffinity }}
        nodeAffinity:
        {{- if .soft }}
{{ toYaml .soft | indent 10 }}
        {{- end }}
        {{- if .hard }}
{{ toYaml .hard | indent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.podAffinity }}
        podAffinity:
        {{- if .soft }}
{{ toYaml .soft | indent 10 }}
        {{- end }}
        {{- if .hard }}
{{ toYaml .hard | indent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.podAntiAffinity }}
        podAntiAffinity:
        {{- if .soft }}
{{ toYaml .soft | indent 10 }}
        {{- end }}
        {{- if .hard }}
{{ toYaml .hard | indent 10 }}
        {{- end }}
      {{- end }}
      # [END affinity]
      # [START tolerations]
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      # [END tolerations]
# [END app container]
# [START init container]
      initContainers:
      {{- if .Values.data.enabled }}
      - name: init-data
        image: busybox
        command: 
        - /bin/sh
        - -c
        - "[ -f /data/a.json ] || date +'%F %T %Z' > /data/a.json"
        volumeMounts:
        - name: data
          mountPath: /data
      {{- end }}
# [END init container]