{{- if .Values.pvc.enabled -}}
{{- $namespace := .Release.Namespace -}}
{{- with .Values.pvc }}
    {{- range .claims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
spec:
{{ toYaml .spec | indent 2 }}
    {{- end }}
{{- end }}
{{- end }}