{{- if .Values.pvc.enabled -}}
{{- with .Values.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .name }}
spec:
  accessModes:
    {{- range .accessModes }}
    - {{ . }}
    {{- end }}
  volumeMode: {{ .volumeMode | default "Filesystem" }}
  resources:
    requests:
      storage: {{ .requests | default "2Gi" }}
    limits:
      storage: {{ .limits | default "10Gi" }}
  storageClassName: {{ .storageClassName | default "standard" }}
{{- end }}
{{- end }}