{{- if not .Values.ingress.tls.existingSecret }}
{{- $namespace := .Release.Namespace -}}
{{- $fullName := include "fortio.fullname" . -}}
{{- with .Values.defaultTLS }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-tls
  namespace: {{ $namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .cert }}
  tls.key: {{ .key }}
{{- end }}
{{- end }}