# Default values for fortio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/nmiu-play/fortio
  tag: latest
  pullPolicy: Always

volume:
  enabled: false
  mounts:
    - name: tls
      mountPath: /tls
    - name: data
      mountPath: /data
  disks:
    - name: tls
      secret:
        secretName: premium-cloud-support-com-tls
    - name: data
      persistentVolumeClaim:
        claimName: fortio-data-pvc

customTLS:
  enabled: false
  secret: premium-cloud-support-com-tls

pvc:
  enabled: false
  name: fortio-data-pvc
  accessModes:
    - ReadWriteOnce
  # volumeModes: Filesystem
  # size: 2Gi
  # storageClassName: standard

service:
  enabled: true
  type: ClusterIP
  # type: LoadBalancer
  # type: NodePort
  externalTrafficPolicy: Local
  # externalTrafficPolicy: Cluster
  sessionAffinity: None
  # sessionAffinity: ClientIP
  ilb: 
    enabled: false
  headless: 
    enabled: false
  http2: 
    enabled: false

  ports:
    grpc:
      enabled: true
      port: 8079
    http:
      enabled: true
      port: 8080
    https:
      enabled: true
      port: 8082

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.global-static-ip-name: asuka
    kubernetes.io/ingress.class: gce
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /*
  servicePort: grpc
  hosts:
    - asuka.premium-cloud-support.com
  tls:
   - secretName: premium-cloud-support-com-tls
     hosts:
       - asuka.premium-cloud-support.com

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector: {}

tolerations:
  - operator: Exists

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - fortio
        topologyKey: "kubernetes.io/hostname"
