# Default values for fortio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/nmiu-play/fortio
  tag: latest
  pullPolicy: Always

data:
  enabled: false
  volume:
    persistentVolumeClaim:
      claimName: fortio-data-pvc

tls:
  enabled: false
  secretName: premium-cloud-support-com-tls
  cert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZRENDQWtnQ0NRRHdVZktTd3dPaUVqQU5CZ2txaGtpRzl3MEJBUXNGQURCeU1Rc3dDUVlEVlFRR0V3SlYKVXpFVE1CRUdBMVVFQ0F3S1EyRnNhV1p2Y201cFlURVdNQlFHQTFVRUJ3d05VMkZ1SUVaeVlXNWphWE5qYnpFTQpNQW9HQTFVRUNnd0RRMUJUTVNnd0pnWURWUVFEREI5aGMzVnJZUzV3Y21WdGFYVnRMV05zYjNWa0xYTjFjSEJ2CmNuUXVZMjl0TUI0WERURTVNRGd4TmpFMU5UVTFNbG9YRFRJNU1EZ3hNekUxTlRVMU1sb3djakVMTUFrR0ExVUUKQmhNQ1ZWTXhFekFSQmdOVkJBZ01Da05oYkdsbWIzSnVhV0V4RmpBVUJnTlZCQWNNRFZOaGJpQkdjbUZ1WTJsegpZMjh4RERBS0JnTlZCQW9NQTBOUVV6RW9NQ1lHQTFVRUF3d2ZZWE4xYTJFdWNISmxiV2wxYlMxamJHOTFaQzF6CmRYQndiM0owTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU03RGNvb0wKTVB1NlMwNmEzL01LOSs3VzNhLzhneWRLU08wbnRQZmJWTlR3NVg0YTRFdlZrWE43L2NtN1BEcHJGb2VtTURGSApZQ2p5ZjlaV3oxTGQ0RFE4bnBtRjRSRi9USGlwM0V1S0dXT1Z5dlJ4QmRQUVpKT1ZPWTFIRnVPZVcxVVloM0NGCkMyMUo3NlpLVGxCQkg0UTZKallWa3BncXN6WHU0Nm4yT3JzemRFY3lVUDdjK01ockJhaHBMOG1DRW1La2xMc1YKN1hQeGpWUEJjOC9YVUZGZTFCYmVlcS9iRnZsbzFQQks2dWd5czlIYVhESklGSkF3SW9jRlBhMm1iRk1IOUxrWAppU3lna1c2Yi82K2RsZnZ4WGNxSDY1OGNMOFVhVkpkUllYRzArTWZBaG1MKytUdW5qSWM5Y1d6UkdJamsyaVhaCkdqb3piUnYweTIwU3VSa0NBd0VBQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWpQemFQb0Z0TXhzS3JpdzEKdytnbGhoZFFhRWhabUlNc0YvZ1JGc1RnM3RvNTNIUHVkckZILzV0YVRGZFl4bkh2V01sRG9NbWhXZUdDakthYwphOFZnUlpCQVhEOHh2ZisvTzQyRVdDZDRXNnMzNEpzWk1HVTF6SlV3blVBbW1udSt0a0U3cDRqN1NZbVlkdG0xCjFLNERGMUFtQzd0VTc4bkc4QThSTVg2MXI2SDA5NHVSL0lMTjVGUWY4ZFpRVjNGNkdVSWsxenEvVU4yRjFwWGoKK29ZWG9hdGUyaUs5d2lJK1N4d3RvL1RiMXpPNkhhWTFxbnh4MzVNSkQzY1kxZlVtak05VkhlcW4vSkVFTXVlTApTQ2VtM2J4azBmekZjU3VFTkFiV08rUDFNUStvLzBMQmxLaE9nTW1Gbm44bU03RmdoY0Jlcm9xN1ZKd1dQaUtECkZ4S3NRUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRE93M0tLQ3pEN3VrdE8KbXQvekN2ZnUxdDJ2L0lNblNranRKN1QzMjFUVThPVitHdUJMMVpGemUvM0p1enc2YXhhSHBqQXhSMkFvOG4vVwpWczlTM2VBMFBKNlpoZUVSZjB4NHFkeExpaGxqbGNyMGNRWFQwR1NUbFRtTlJ4YmpubHRWR0lkd2hRdHRTZSttClNrNVFRUitFT2lZMkZaS1lLck0xN3VPcDlqcTdNM1JITWxEKzNQaklhd1dvYVMvSmdoSmlwSlM3RmUxejhZMVQKd1hQUDExQlJYdFFXM25xdjJ4YjVhTlR3U3Vyb01yUFIybHd5U0JTUU1DS0hCVDJ0cG14VEIvUzVGNGtzb0pGdQptLyt2blpYNzhWM0toK3VmSEMvRkdsU1hVV0Z4dFBqSHdJWmkvdms3cDR5SFBYRnMwUmlJNU5vbDJSbzZNMjBiCjlNdHRFcmtaQWdNQkFBRUNnZ0VBZks2ZmcxNzhTdEFzV1ZwTGNlUkxYbHR6azR4U0NuOWhPcUdYSDEvRDZDVGMKUHc4MThvVDNFUXpVSGJJcXY0K1VKbml3MXdhVGxoMmx1VHJnQ3JpQld2NnpKU0QyZC9hcnhwZW5vR1hHcWFiSwpuRjBMaG85RUZ6c0ZXWXhrNFIyOU5iTjArUVZCdnNXM0hpL3d5YlI3ck9EajZmbFlUU3B5cHpOSFZsYUZWQnk5CnAvMDhiL09BWk94Qjd1bDVWTFpDT1FSaThhVTZUajdDak1KU2dWcG5DMEhvTjhhaEUzYU5rQTRzbFhWUmZBSTIKc1UraU1GVytDSWJpUlZMN3F1VXlSdjRCNnBzR2ZRV2NRWDExeTVMTEJLNGhmc3hkZWNXekZORmIrVW5IRDN3MApDSUU4N1ExemxuREExU05Uc1VuMEVFMWFCYkNlbU9HV3d5Ylc0NUtMZ1FLQmdRRG1kQUVNT29GK2J0TTJJT0ZqCkJpNXJISU1ZZzJycnFRTGl4K3JUanZtOFU2N1c4NEZuWEl1Q3NHZk1ZWmI0enJnamNvdTNubHVuc1kydEVEalUKZmJxTitydCtBc0ZFamEwclJIc2dhNXdiRmtoQzJGNXdKUktVSlAxZ2J5OHU2NHFpaVhYMEIyK1JlT0pIK1FKWQpwemlxaFJFTG5UamdYWUNsdmV3Z0Q5MlVqd0tCZ1FEbHJ5aFRtellQY0ZBTGQzN1ZSZ1l2eHdWUi90RjhMR2I5CnpSbzAyc3ZuZmJ1dGxLZFVxTVI3a3oyVlNEWjk2QVJKK2JJRHVSU0x4RWI1b21ZQkpJUFVHOTlmY0xWTllPUzUKcDhrSjZJbFFkVnJxK3BJdnh1dXMzYVlSdXRzWWN4TGovMWhzdnYydGwydGNrQkhLRTR6K2lCRk41R0tpUmYvSgowdldqTm1JNzF3S0JnUURqQklQRHVCNjRuaFFTem5FNVMyMk90cGV1SGtmRnZzakkvb2Vsd01MamNzeFprNmQyCld3UlR5ZE4yMHV3V1RnMjNYYStsUXFxbmw1RXBXMEdna2Zxa3dzclFaNFpjTWZUVkdyRHdUeEdJM1hweDN4T3AKQmR3M2Mvam1kcURVWjlRNktZKzR4VnB5dzlLbGMvZUx2YTlreTVEdkVBSm5nN1Nua1dCNmRTYWlvUUtCZ1FDNwpSa0lmU1dLZTIvaW9JTnF0a3RiZ2hlbjBuVXk1Ym9yYlRpeWNBL3BWMmRMNUNVZ1dZelV4ZlRDdFU1LzZzUDh1ClFnVy91MXpoU1R5RnRzQnRGaFRYRVpMa0FzWVJQWHZCVk9rNnh2dVBPdURTejFQNjJMcTR6RkRvQys4dzFFTUcKMitDQmFvajB6WTJnZjJmQjJJY1IwbWdwbHBwRnJjV09EaEJ5NzVqUktRS0JnRW00SU05bnJnMmtrT0dTK0REMAp4L0hoTG1YWXR5VDdoMk9aUGttTFdnNFFMYzd6ZFdTUCtwejh4eEdkS1RrbFh2Y0VDYi9hdzFGaXNVTi9tbm8xCmk4Z0hFMDBwc0N2aVJSWERJMlpSMVZaWm03dFdEMVRQSU9hbUdHcnVQYWgvSXZ0UUlrcXpZR0lZdjlIUjhyU20KODh5Q2FiU1RLVGpuTldkUnYwZElTYW10Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"

pvc:
  enabled: false
  claims: 
    - name: fortio-data-pvc
      spec:
        accessModes:
        - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 2Gi
          limits:
            storage: 10Gi
        storageClassName: standard
    # - name: test-pvc
    #   spec:
    #     accessModes:
    #       - ReadWriteOnce
    #     volumeMode: Filesystem
    #     resources:
    #       requests:
    #         storage: 2Gi
    #       limits:
    #         storage: 3Gi
    #     storageClassName: standard

service:
  enabled: false
  type: ClusterIP
  # type: LoadBalancer
  # type: NodePort
  externalTrafficPolicy: Local
  # externalTrafficPolicy: Cluster
  sessionAffinity: None
  # sessionAffinity: ClientIP
  ilb: false
  headless: false
  http2: false

  ports:
    grpc:
      port: 8079
    http:
      port: 8080
    https:
      port: 8082

ingress:
  enabled: false
  neg: false
  nginx: false
  annotations:
    gce: 
      kubernetes.io/ingress.global-static-ip-name: asuka
      kubernetes.io/ingress.class: gce
    nginx:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
      # kubernetes.io/tls-acme: "true"
  path: /
  # path: /*
  servicePort: http
  # servicePort: https
  # servicePort: grpc
  hosts:
  - asuka.premium-cloud-support.com
  tls:
  - secretName: premium-cloud-support-com-tls
    hosts:
      - asuka.premium-cloud-support.com

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector: {}

tolerations:
- operator: Exists # tolerates everything

nodeAffinity:
  soft:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-central1-a
  hard:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - us-central1-a

podAffinity:
  soft:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - foo
        topologyKey: "kubernetes.io/hostname"
  hard:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - foo
      topologyKey: "kubernetes.io/hostname"

podAntiAffinity:
  soft:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - fortio
          - key: release
            operator: In
            values:
            - RELEASE
        topologyKey: "kubernetes.io/hostname"
  hard:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - fortio
        - key: release
          operator: In
          values:
          - RELEASE
      topologyKey: "kubernetes.io/hostname"

## values for dependencies
nginx-ingress:

  controller:
    replicaCount: 2

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - RELEASE-nginx-ingress
          topologyKey: "kubernetes.io/hostname"