---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "go-web.frontend" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "go-web.name" . }}
    chart: {{ template "go-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - port: 50000
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ template "go-web.name" . }}
    tier: frontend
    release: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "go-web.backend" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "go-web.name" . }}
    chart: {{ template "go-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - port: 50000
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ template "go-web.name" . }}
    tier: backend
    release: {{ .Release.Name }}
